package cn.vcampus.common;

/** Stable message names shared by client and server. */
public enum MessageType {
    REGISTER, UNREGISTER, LOGIN, LOGOUT, AUTHORIZE,
    STUDENT_QUERY, STUDENT_UPDATE, STUDENT_REVIEW,
    COURSE_QUERY, COURSE_SELECT, COURSE_DROP, COURSE_CREATE, COURSE_UPDATE, COURSE_DEACTIVATE, COURSE_GRADE_WRITE,
    LIBRARY_QUERY, LIBRARY_BORROW, LIBRARY_RETURN,
    STORE_QUERY, STORE_PURCHASE, STORE_ORDER_QUERY
}
