package cn.vcampus.common;

/** Stable message names shared by client and server. */
public enum MessageType {
    REGISTER, UNREGISTER, LOGIN, LOGOUT, AUTHORIZE, USER_LIST, USER_IMPORT,
    USER_ENABLE, USER_DISABLE, USER_ROLE_CHANGE, USER_AUDIT_LIST,
    PASSWORD_RESET_REQUEST, PASSWORD_RESET_LIST, PASSWORD_RESET_REVIEW, PASSWORD_CHANGE,
    STUDENT_QUERY, STUDENT_UPDATE,
    COURSE_QUERY, COURSE_SELECT, COURSE_DROP, COURSE_CREATE, COURSE_UPDATE, COURSE_DEACTIVATE,
    COURSE_MANAGE,
    COURSE_SELECTION_QUERY_V2, COURSE_SELECT_OFFERING_V2, COURSE_DROP_RECORD_V2,
    LIBRARY_QUERY, LIBRARY_BORROW, LIBRARY_RETURN, STORE_QUERY, STORE_PURCHASE, STORE_ORDER_QUERY
}
